### ISSUE TITLE
Issue with negative Oid values

### ISSUE THREAD

**Issue by virtuallynathan** [cdevr/WapSNMP#11]
A value like -91 (as reported by snmpget) returns as 16777125 in WapSNMP. 

I havent found the cause yet, but i'll do a pull request if i find it.

**Comment by cdevr** [comment]
Trying some creative stuff to get DecodeInteger to fail

**Comment by codedance** [comment]
Your BER parsing code is layed out quite a bit better, but the code in soniah's work is correct for all the real-world cases we've managed to find:

See func parseInt*

https://github.com/soniah/gosnmp/blob/master/helper.go

**Comment by cdevr** [comment]
I've included the sign extension code and found a few binary dumps. Typing should now be more accurate for ber types as well.

I think this will work now.

**Comment by cdevr** [comment]
Solved in 9063268c39c2117eee22f7f6a1a6b261492ef2a4
