### ISSUE TITLE
udp_stub_connection.go and flag.PrintDefaults()

### ISSUE THREAD

**Issue by 42wim** [cdevr/WapSNMP#15]
When the udp_stub_connection.go file exists flag.PrintDefaults will add test parameters on output.
Maybe because of udpStub struct ?

$ ./mysnmp -h
Usage of ./mysnmp:
  -host="": host
  -test.bench="": regular expression to select benchmarks to run
  -test.benchmem=false: print memory allocations for benchmarks
  -test.benchtime=1s: approximate run time for each benchmark
....

**Comment by cdevr** [comment]
It seems this is happening because it's a file only used for tests that doesn't have the _test.go at the end of it's filename.
