### ISSUE TITLE
EncodeInteger/EncodeUint Issue

### ISSUE THREAD

**Issue by wiiittttt** [cdevr/WapSNMP#20]
Looks like EncodeInteger and EncodeUint produce the wrong byte array for some values.

Example:
encodedID := wapsnmp.EncodeInteger(int64(16495265))
// encodedID = [251 178 161]
// should be [0 251 178 161]

This causes the value to be decoded as -281951 instead of 16495265.

Here are some more.

|RequestID|   Encoded   |Decoded |
|---------|-------------|--------|
|16495265 |[251 178 161]|-281951 |
|9544834  |[145 164 130]|-7232382|
|10479253 |[159 230 149]|-6297963|
|14231300 |[217 39 4]   |-2545916|
|16167221 |[246 177 53] |-609995 |
|9640701  |[147 26 253] |-7136515|
|16474587 |[251 97 219] |-302629 |
|11990425 |[182 245 153]|-4786791|
|9237227  |[140 242 235]|-7539989|

**Comment by wiiittttt** [comment]
I think just this line may need to be changed?

```
if toEncode > 0 {
    for i := toEncode; i > 255; i >>= 8 {
        l++
    }
}
```

to

```
if toEncode > 0 {
    for i := toEncode; i > 0; i >>= 8 {
        l++
    }
}
```

**Comment by cdevr** [comment]
Yeah the encoded values are wrong. They should be prefixed with "00". For example:

|RequestID|   Encoded   |Decoded |
|---------|-------------|--------|
|16495265 |[0 251 178 161]|-281951 |

Let's see if I can fix.

**Comment by cdevr** [comment]
Spent a lot of effort trying to get it into the general case. #@$^_@#^*_!@$#@# Not working.

Fixing by special casing it instead.

**Comment by cdevr** [comment]
Issue should be fixed, test added.

**Comment by wiiittttt** [comment]
Awesome. Thanks.
